# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

email: contact@cassisdev.com
description: >
  Services de développement d'applications web Ruby on Rails sur mesure en freelance

t:
  en:
    title: cassisdev - Ruby on Rails development services
    description: >
      Freelance Ruby on Rails web application development services. Available in Lille or remote working
  fr:
    title: cassisdev - Services de développement d'applications web Ruby on Rails - Lille
    description:  >
      Services freelance de développement d'applications web Ruby on Rails sur mesure. Disponible à Lille ou en télétravail

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cassisdev.com" # the base hostname & protocol for your site
twitter_username: cassisdev
github_username:  cassisdev

# Build settings
markdown: kramdown
