# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

email: contact@cassisdev.com

t:
  en:
    title: "Cassisdev: Freelance Ruby on Rails development"
    description: >
      Freelance Ruby on Rails web application development: design, implementation, optimisation.
      Available in Lille or for remote working. Contact me
  fr:
    title: "Cassisdev : Développment Ruby on Rails - Freelance, Lille"
    description:  >
      Développement d'applications web Ruby on Rails Freelance : conception, réalisation, optimisation.
      Disponible à Lille ou en travail à distance. Contactez-moi

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cassisdev.com" # the base hostname & protocol for your site
twitter_username: cassisdev
github_username:  cassisdev

# Build settings
markdown: kramdown
